/* Generated by scripts/vendor-assets.js — do not edit. Font files live in /fonts. */
(function (root) {
  'use strict';
  const ns = root.ADHDR || (root.ADHDR = {});
  ns.FONT_FACES = [
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "400",
      "file": "atkinson-hyperlegible-next-latin-ext-400-normal.woff2",
      "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "400",
      "file": "atkinson-hyperlegible-next-latin-400-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "700",
      "file": "atkinson-hyperlegible-next-latin-ext-700-normal.woff2",
      "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "700",
      "file": "atkinson-hyperlegible-next-latin-700-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "800",
      "file": "atkinson-hyperlegible-next-latin-ext-800-normal.woff2",
      "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "normal",
      "weight": "800",
      "file": "atkinson-hyperlegible-next-latin-800-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "italic",
      "weight": "400",
      "file": "atkinson-hyperlegible-next-latin-ext-400-italic.woff2",
      "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
    },
    {
      "family": "ADHDR Atkinson",
      "style": "italic",
      "weight": "400",
      "file": "atkinson-hyperlegible-next-latin-400-italic.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR Lexend",
      "style": "normal",
      "weight": "100 900",
      "file": "lexend-latin-ext-wght-normal.woff2",
      "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
    },
    {
      "family": "ADHDR Lexend",
      "style": "normal",
      "weight": "100 900",
      "file": "lexend-latin-wght-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR OpenDyslexic",
      "style": "normal",
      "weight": "400",
      "file": "opendyslexic-latin-400-normal.woff2"
    },
    {
      "family": "ADHDR OpenDyslexic",
      "style": "normal",
      "weight": "700",
      "file": "opendyslexic-latin-700-normal.woff2"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "normal",
      "weight": "400",
      "file": "pt-sans-cyrillic-400-normal.woff2",
      "range": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "normal",
      "weight": "400",
      "file": "pt-sans-latin-400-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "normal",
      "weight": "700",
      "file": "pt-sans-cyrillic-700-normal.woff2",
      "range": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "normal",
      "weight": "700",
      "file": "pt-sans-latin-700-normal.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "italic",
      "weight": "400",
      "file": "pt-sans-cyrillic-400-italic.woff2",
      "range": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116"
    },
    {
      "family": "ADHDR PT Sans",
      "style": "italic",
      "weight": "400",
      "file": "pt-sans-latin-400-italic.woff2",
      "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
    }
  ];
})(globalThis);
