/*
 * Copies third-party assets from node_modules into the extension and generates
 * src/content/font-faces.js. The outputs are committed, so the extension loads without npm.
 *
 * Usage: npm run vendor   (after npm install)
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const MODULES = path.join(ROOT, 'node_modules');

// Family names get an "ADHDR" prefix so they never clash with fonts a page declares itself.
const FONTS = [
  {
    family: 'ADHDR Atkinson',
    pkg: '@fontsource/atkinson-hyperlegible-next',
    css: ['400.css', '700.css', '800.css', '400-italic.css'],
    subsets: ['latin', 'latin-ext'],
  },
  { family: 'ADHDR Lexend', pkg: '@fontsource-variable/lexend', css: ['wght.css'], subsets: ['latin', 'latin-ext'] },
  { family: 'ADHDR OpenDyslexic', pkg: '@fontsource/opendyslexic', css: ['400.css', '700.css'], subsets: ['latin'] },
  { family: 'ADHDR PT Sans', pkg: '@fontsource/pt-sans', css: ['400.css', '700.css', '400-italic.css'], subsets: ['latin', 'cyrillic'] },
];

// Per-weight CSS files list every subset with its unicode-range; the subset is in the file name.
const SUBSET_RE = /-(latin-ext|latin|cyrillic-ext|cyrillic|greek-ext|greek|vietnamese)-(?:\d+|wght)-/;

function parseFaces(cssText) {
  const faces = [];
  for (const [, comment, body] of cssText.matchAll(/\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*{([^}]*)}/g)) {
    const prop = (name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim();
    const file = body.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
    faces.push({ id: comment, style: prop('font-style'), weight: prop('font-weight'), range: prop('unicode-range'), file });
  }
  return faces;
}

const outDir = path.join(ROOT, 'fonts');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir);

const faces = [];
const licenses = [];
for (const font of FONTS) {
  const pkgDir = path.join(MODULES, font.pkg);
  for (const cssFile of font.css) {
    for (const face of parseFaces(fs.readFileSync(path.join(pkgDir, cssFile), 'utf8'))) {
      if (!font.subsets.includes(face.file.match(SUBSET_RE)?.[1])) continue;
      fs.copyFileSync(path.join(pkgDir, 'files', face.file), path.join(outDir, face.file));
      faces.push({ family: font.family, style: face.style, weight: face.weight, file: face.file, range: face.range });
    }
  }
  const { version } = JSON.parse(fs.readFileSync(path.join(pkgDir, 'package.json'), 'utf8'));
  licenses.push(`${font.family.replace('ADHDR ', '')} — ${font.pkg}@${version}\n\n${fs.readFileSync(path.join(pkgDir, 'LICENSE'), 'utf8').trim()}`);
}
fs.writeFileSync(path.join(outDir, 'LICENSES.txt'), `Fonts bundled with ADHD Reader (SIL Open Font License 1.1)\n\n${licenses.join('\n\n----------------------------------------\n\n')}\n`);

fs.writeFileSync(
  path.join(ROOT, 'src/content/font-faces.js'),
  `/* Generated by scripts/vendor-assets.js — do not edit. Font files live in /fonts. */\n` +
    `(function (root) {\n  'use strict';\n  const ns = root.ADHDR || (root.ADHDR = {});\n` +
    `  ns.FONT_FACES = ${JSON.stringify(faces, null, 2).replace(/\n/g, '\n  ')};\n})(globalThis);\n`,
);

const vendorDir = path.join(ROOT, 'src/vendor');
fs.mkdirSync(vendorDir, { recursive: true });
const readability = path.join(MODULES, '@mozilla/readability');
fs.copyFileSync(path.join(readability, 'Readability.js'), path.join(vendorDir, 'Readability.js'));
fs.copyFileSync(path.join(readability, 'LICENSE.md'), path.join(vendorDir, 'Readability.LICENSE.md'));

const total = fs.readdirSync(outDir).reduce((sum, f) => sum + fs.statSync(path.join(outDir, f)).size, 0);
console.log(`${faces.length} font faces, ${(total / 1024).toFixed(0)} KB in fonts/; Readability copied to src/vendor/`);
